export const cuisineList = [
    { id: 1, label: "American" },
    { id: 2, label: "BBQ" },
    { id: 3, label: "Breakfast" },
    { id: 4, label: "Burgers" },
    { id: 5, label: "Cafe" },
    { id: 6, label: "Chinese" },
    { id: 7, label: "Desserts" },
    { id: 8, label: "French" },
    { id: 9, label: "Greek" },
    { id: 10, label: "Healthy" },
    { id: 11, label: "Indian" },
    { id: 12, label: "Italian" },
    { id: 13, label: "Japanese" },
    { id: 14, label: "Mexican" },
    { id: 15, label: "Noodles" },
    { id: 16, label: "Organic" },
    { id: 17, label: "Pasta" },
    { id: 18, label: "Pizza" },
    { id: 19, label: "Salads" },
    { id: 20, label: "Seafood" },
    { id: 21, label: "Spanish" },
    { id: 22, label: "Steak" },
    { id: 23, label: "Sushi" },
    { id: 24, label: "Tacos" },
    { id: 25, label: "Tapas" },
    { id: 26, label: "Vegan" },
  ];
  